#!/bin/sh -eu

. $(dirname $0)/../core/setup.sh

banner Display Version
#---------------------

$HADRON -v | grep -q hadron

$HADRON --version

banner Display Help
#------------------

$HADRON -h

$HADRON --help

HADRON="$HADRON --dry-run"

$HADRON validate
